code_syntax_highlight = "matugen"

# ========= Border =========
file_panel_border = "#4a454e"
sidebar_border = "#151218"
footer_border = "#4a454e"

# ========= Border Active =========
file_panel_border_active = "#c8adec"
sidebar_border_active = "#93000a"
footer_border_active = "#6b538c"
modal_border_active = "#4a454e"

# ========= Background (bg) =========
full_screen_bg = "#151218"
file_panel_bg = "#151218"
sidebar_bg = "#151218"
footer_bg = "#151218"
modal_bg = "#151218"

# ========= Foreground (fg) =========
full_screen_fg = "#958e99"
file_panel_fg = "#958e99"
sidebar_fg = "#958e99"
footer_fg = "#958e99"
modal_fg = "#958e99"

# ========= Special Color =========
cursor = "#ffdad6"
correct = "#6b538c"
error = "#93000a"
hint = "#653b43"
cancel = "#ffb4ab"
# Gradient color can only have two color!
gradient_color = ["#321019", "#d6bbfb"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#6b538c"
file_panel_top_path = "#f2b7c2" 
file_panel_item_selected_fg = "#f2b7c2"
file_panel_item_selected_bg = "#151218"

# ========= Sidebar Special Items =========
sidebar_title = "#d6bbfb"
sidebar_item_selected_fg = "#ffd9df"
sidebar_item_selected_bg = "#151218"
sidebar_divider = "#4a454e"

# ========= Modal Special Items =========
modal_cancel_fg = "#37333a"
modal_cancel_bg = "#ffb4ab"

modal_confirm_fg = "#37333a"
modal_confirm_bg = "#ffd9df"

# ========= Help Menu =========
help_menu_hotkey = "#ffd9df"
help_menu_title = "#ffb4ab"
