code_syntax_highlight = "matugen"

# ========= Border =========
file_panel_border = "#46464f"
sidebar_border = "#131318"
footer_border = "#46464f"

# ========= Border Active =========
file_panel_border_active = "#7b82c6"
sidebar_border_active = "#93000a"
footer_border_active = "#545a92"
modal_border_active = "#46464f"

# ========= Background (bg) =========
full_screen_bg = "#131318"
file_panel_bg = "#131318"
sidebar_bg = "#131318"
footer_bg = "#131318"
modal_bg = "#131318"

# ========= Foreground (fg) =========
full_screen_fg = "#91909a"
file_panel_fg = "#91909a"
sidebar_fg = "#91909a"
footer_fg = "#91909a"
modal_fg = "#91909a"

# ========= Special Color =========
cursor = "#ffdad6"
correct = "#545a92"
error = "#93000a"
hint = "#5e3c53"
cancel = "#ffb4ab"
# Gradient color can only have two color!
gradient_color = ["#2e1126", "#bdc2ff"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#545a92"
file_panel_top_path = "#e7b9d6" 
file_panel_item_selected_fg = "#e7b9d6"
file_panel_item_selected_bg = "#131318"

# ========= Sidebar Special Items =========
sidebar_title = "#bdc2ff"
sidebar_item_selected_fg = "#ffd7ef"
sidebar_item_selected_bg = "#131318"
sidebar_divider = "#46464f"

# ========= Modal Special Items =========
modal_cancel_fg = "#34343a"
modal_cancel_bg = "#ffb4ab"

modal_confirm_fg = "#34343a"
modal_confirm_bg = "#ffd7ef"

# ========= Help Menu =========
help_menu_hotkey = "#ffd7ef"
help_menu_title = "#ffb4ab"
