code_syntax_highlight = "matugen"

# ========= Border =========
file_panel_border = "#51443a"
sidebar_border = "#19120c"
footer_border = "#51443a"

# ========= Border Active =========
file_panel_border_active = "#7c726b"
sidebar_border_active = "#93000a"
footer_border_active = "#87521b"
modal_border_active = "#51443a"

# ========= Background (bg) =========
full_screen_bg = "#19120c"
file_panel_bg = "#19120c"
sidebar_bg = "#19120c"
footer_bg = "#19120c"
modal_bg = "#19120c"

# ========= Foreground (fg) =========
full_screen_fg = "#9e8e82"
file_panel_fg = "#9e8e82"
sidebar_fg = "#9e8e82"
footer_fg = "#9e8e82"
modal_fg = "#9e8e82"

# ========= Special Color =========
cursor = "#ffdad6"
correct = "#87521b"
error = "#93000a"
hint = "#434a23"
cancel = "#ffb4ab"
# Gradient color can only have two color!
gradient_color = ["#181e00", "#ffb878"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#87521b"
file_panel_top_path = "#c3cb98" 
file_panel_item_selected_fg = "#c3cb98"
file_panel_item_selected_bg = "#19120c"

# ========= Sidebar Special Items =========
sidebar_title = "#ffb878"
sidebar_item_selected_fg = "#dfe8b2"
sidebar_item_selected_bg = "#19120c"
sidebar_divider = "#51443a"

# ========= Modal Special Items =========
modal_cancel_fg = "#3c332c"
modal_cancel_bg = "#ffb4ab"

modal_confirm_fg = "#3c332c"
modal_confirm_bg = "#dfe8b2"

# ========= Help Menu =========
help_menu_hotkey = "#dfe8b2"
help_menu_title = "#ffb4ab"
