general {
    lock_cmd = pidof hyprlock || hyprlock; [ "$(pgrep -c waybar)" -ge 2 ] && pkill waybar || true
    #unlock_cmd = pkill -SIGUSR2 waybar
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
    timeout = 180 # 3 minutes
    on-timeout = $HOME/.config/hypr/hyprland/scripts/brightness.sh set 20
    on-resume = sleep 5 && $HOME/.config/hypr/hyprland/scripts/brightness.sh revert
}

listener {
    timeout = 270                                 # 4.5min
    on-timeout = loginctl lock-session
}

listener {
    timeout = 330                                 # 5.5min
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'        # screen off when timeout has passed
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'          # screen on when activity is detected after timeout has fired. & Stop waybar from multiplying
}

# listener {
#     timeout = 900                                 # 15min
#     on-timeout = systemctl suspend                # suspend pc
# }
