hl.on("hyprland.start", function ()
  hl.exec_cmd("hyprlock && hyprctl reload")
  hl.exec_cmd("hyprpaper")
  hl.exec_cmd("hypridle")
  hl.exec_cmd("hyprsunset")
  hl.exec_cmd("/usr/lib/hyprpolkitagent/hyprpolkitagent")
  hl.exec_cmd("systemctl start waybar --user")
  hl.exec_cmd("mako")

  hl.exec_cmd("dbus-update-activation-environment --all --systemd")
  hl.exec_cmd("systemctl --user import-environment QT_QPA_PLATFORMTHEME WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
  hl.exec_cmd("hyprpm reload")
  hl.exec_cmd("wl-paste -t text --watch clipman store -P --histpath='/tmp/clipman.json'")

  hl.exec_cmd("hyprctl setcursor 'catppuccin-mocha-dark-cursors' 24")
  hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-size 18")
  hl.exec_cmd("gsettings set org.gnome.desktop.interface cursor-theme 'catppuccin-mocha-dark-cursors'")
  hl.exec_cmd("gsettings set org.gnome.desktop.interface icon-theme 'Papirus-Dark'")
  hl.exec_cmd("gsettings set org.gnome.desktop.interface font-name 'JetBrains Mono Nerd Font'")
  hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme 'Matugen'")
  hl.exec_cmd("mako")
end)
