#!/usr/bin/env sh

DATE=$(date +"%Y-%m-%d_%H-%M-%S")

if pgrep -x wf-recorder >/dev/null; then
    printf '{"text":" Rec","class":"enabled"}'
    pkill wf-recorder
else
    printf '{"text":" Rec"}'
    wf-recorder -g "$(slurp)" -a --file=${DATE}.mp4
fi
